version: "3.5"
services:
  aicap-tech:
    container_name: karmo-test
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: sh -c "npm install && npm run dev" # development enviroment
    # command: sh -c "npm install && npm run test && npm run build && npm run start" # production enviroment
